url: http://sakuragroup.co
# url: http://127.0.0.1:4000

#baseurl: /agency-jekyll-theme/

# Site settings
title: The Sakura Group
email: taka@sakuragroup.co
description: "Portland Oregon - Design / Build / Remodel"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 262d37
  secondary: 262d37
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Taka Nakagawa
  pic: 1
  position: Founder / Project Manager
  email: taka@sakuragroup.co
  telephone: +1 (503) 680-4463
  biography:
  social:
    - title: twitter
      url: http://twitter.com/thesakuragroup
    - title: facebook
<<<<<<< HEAD
      url: https://www.facebook.com/thesakuragroup
    - title: pinterest
      url: https://www.pinterest.com/gdeim3178/
=======
      url: https://www.facebook.com/taka.nakagawa.9

>>>>>>> master
- name: Doug Johnson
  pic: 2
  position: Assistant Project Manager
  email: douglasljohnson@outlook.com
  telephone: +1 (503) XXXXXXX
  biography:
  social:
    - title:
      url:
    - title:
      url:
- name: Kevin Tocke
  pic: 3
  position: Project Manager/Lead Carpenter
  email:
  telephone:
  biography:
  social:
    - title:
      url:
    - title:
      url:


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thesakuragroup
  - title: facebook
    url: http://facebook.com/thesakuragroup

# Postal address (add as many lines as necessary)
address:
<<<<<<< HEAD
  - line: 2010 SE 7th Ave
  - line: Portland, OR 90210
=======
  - line: 1020 #15235 SE 7th Ave 
  - line: Portland, OR 97214
>>>>>>> master

# Build settings
markdown: kramdown
permalink: pretty
