url: http://sakuragroup.co
#baseurl: /agency-jekyll-theme/

# Site settings
title: The Sakura Group
email: josh@sakuragroup.co
description: "Portland Oregon - Design / Build / Remodel"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 262d37
  secondary: 262d37
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Taka Nakagawa
  pic: 1
  position: Founder / Project Manager
  email: taka@sakuragroup.co
  telephone: +1 (503) 451-5944
  biography:
  social:
    - title: twitter
      url: http://twitter.com/thesakuragroup
    - title: facebook
      url: https://www.facebook.com/taka.nakagawa.9

- name: Joshua Vaage
  pic: 2
  position: Builder / Assistant Project Manager
  email: josh@sakuragroup.co
  telephone: +1 (503) 863-6014
  social:
    - title: twitter
      url: http://twitter.com/whaleen
    - title: facebook
      url: http://facebook.com/joshuavaage

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thesakuragroup
  - title: facebook
    url: http://facebook.com/thesakuragroup

# Postal address (add as many lines as necessary)
address:
  - line: 2010 SE 7th Ave 
  - line: Portland, OR 90210

# Build settings
markdown: kramdown
permalink: pretty