url: https://whaleen.github.io
baseurl: sakuragroup.co

# Site settings
title: The Sakura Group
email: mail@sakuragroup.co
description: "Portland Oregon - Design / Build / Remodel"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 262d37
  secondary: fd6a4f
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Taka Nakagawa
  pic: 1
  position: Founder / Project Manager
  biography:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #

- name: Joshua Vaage
  pic: 2
  position: Builder / Site Manager
  social:
    - title: twitter
      url: http://twitter.com/whaleen
    - title: facebook
      url: http://facebook.com/joshuavaage

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thesakuragroup
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 2010 SE 7th Ave 
  - line: Portland, OR 90210

# Build settings
markdown: kramdown
permalink: pretty